version: '3'

services:
###> doctrine/doctrine-bundle ###
  api:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - api
###< doctrine/doctrine-bundle ###

networks:
  api: